# web:
#   image: nacyot/graphite-web
#   ports:
#     - "80:80"

relay:
  image: registry.banno-internal.com/carbon-relay
  ports:
    - "2003:2003"
    - "2004:2004"
    - "7002:7002"

# carbon1:
#   image: nacyot/carbon-cache
#   ports:
#     - "7012:7002"
#     - "2013:2003"
#     - "2014:2004"

# carbon2:
#   image: nacyot/carbon-cache
#   ports:
#     - "7022:7002"
#     - "2023:2003"
#     - "2024:2004"

# carbon3:
#   image: nacyot/carbon-cache
#   ports:
#     - "7032:7002"
#     - "2033:2003"
#     - "2034:2004"