grafana:
  image: banno/grafana
  ports:
    - "80:8081"
  links:
    - web
    - elasticsearch

haproxy:
  image: banno/graphite-haproxy
  net: host
  links:
    - relay

elasticsearch:
  image: banno/graphite-elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

web:
  image: banno/graphite-web
  environment:
    CLUSTER_SERVERS: weba:80,webb:80
  ports:
    - "8080:80"
  links:
    - weba
    - webb

relay:
  image: banno/carbon-relay
  ports:
    - "3003:2003"
    - "3004:2004"
  environment:
    RELAY_METHOD: consistent-hashing
    DESTINATIONS: relaya:2104, relayb:2204
  links:
    - relaya
    - relayb

weba:
  image: banno/graphite-web
  volumes_from:
    - whisper
  environment:
    CARBONLINK_HOSTS: cache1a:7012,cache2a:7022
    WHISPER_DIR: /opt/graphite/storage/whispera
  ports:
    - "8180:80"
  links:
    - cache1a
    - cache2a

relaya:
  image: banno/carbon-relay
  ports:
    - "2103:2103"
    - "2104:2104"
  environment:
    LINE_RECEIVER_PORT: 2103
    PICKLE_RECEIVER_PORT: 2104
    RELAY_METHOD: consistent-hashing
    DESTINATIONS: cache1a:2014:1a, cache2a:2024:2a
  links:
    - cache1a
    - cache2a

cache1a:
  image: banno/carbon-cache
  volumes_from:
    - whisper
  ports:
    - "7012:7012"
    - "2013:2013"
    - "2014:2014"
  environment:
    NODE_NAME: cache:1a
    LINE_RECEIVER_PORT: 2013
    PICKLE_RECEIVER_PORT: 2014
    CACHE_QUERY_PORT: 7012
    LOCAL_DATA_DIR: /opt/graphite/storage/whispera
  command: --instance=1a

cache2a:
  image: banno/carbon-cache
  volumes_from:
    - whisper
  ports:
    - "7022:7022"
    - "2023:2023"
    - "2024:2024"
  environment:
    NODE_NAME: cache:2a
    LINE_RECEIVER_PORT: 2023
    PICKLE_RECEIVER_PORT: 2024
    CACHE_QUERY_PORT: 7022
    LOCAL_DATA_DIR: /opt/graphite/storage/whispera
  command: --instance=2a

webb:
  image: banno/graphite-web
  volumes_from:
    - whisper
  environment:
    CARBONLINK_HOSTS: cache1b:7112,cache2b:7122
    WHISPER_DIR: /opt/graphite/storage/whisperb
  ports:
    - "8280:80"
  links:
    - cache1b
    - cache2b

relayb:
  image: banno/carbon-relay
  ports:
    - "2203:2203"
    - "2204:2204"
  environment:
    LINE_RECEIVER_PORT: 2203
    PICKLE_RECEIVER_PORT: 2204
    RELAY_METHOD: consistent-hashing
    DESTINATIONS: cache1b:2114:1b, cache2b:2124:2b
  links:
    - cache1b
    - cache2b

cache1b:
  image: banno/carbon-cache
  volumes_from:
    - whisper
  ports:
    - "7112:7112"
    - "2113:2113"
    - "2114:2114"
  environment:
    NODE_NAME: cache:1b
    LINE_RECEIVER_PORT: 2113
    PICKLE_RECEIVER_PORT: 2114
    CACHE_QUERY_PORT: 7112
    LOCAL_DATA_DIR: /opt/graphite/storage/whisperb
  command: --instance=1b

cache2b:
  image: banno/carbon-cache
  volumes_from:
    - whisper
  ports:
    - "7122:7122"
    - "2123:2123"
    - "2124:2124"
  environment:
    NODE_NAME: cache:2b
    LINE_RECEIVER_PORT: 2123
    PICKLE_RECEIVER_PORT: 2124
    CACHE_QUERY_PORT: 7122
    LOCAL_DATA_DIR: /opt/graphite/storage/whisperb
  command: --instance=2b

whisper:
  image: busybox
  volumes:
    - /tmp/whispera:/opt/graphite/storage/whispera
    - /tmp/whisperb:/opt/graphite/storage/whisperb

test:
  build: ./test
  links:
    - grafana
    - web
    - relay
  volumes_from:
    - whisper
